version: "3.6"

services:

  cleos:

    build:
      context: .
      args:
        - VER=${VER}

    image: varilink/eosio:${VER}

    entrypoint: cleos.sh

    depends_on:
      - keosd

  keosd:

    build:
      context: .
      args:
        - VER=${VER}

    image: varilink/eosio:${VER}

    container_name: eosio-keosd

    entrypoint: keosd.sh

    expose:
      - "8888"

    volumes:
      - wallet:/wallet

  nodeos:

    build:
      context: .
      args:
        - VER=${VER}

    image: varilink/eosio:${VER}

    container_name: eosio-nodeos

    entrypoint: nodeos.sh

    command:
      --http-server-address eosio-nodeos:8888
      --plugin eosio::chain_api_plugin

    expose:
      - "8888"

    volumes:
      - ./config:/config
      - data:/data

  snapshot:

    build:
      context: .
      args:
        - VER=${VER}

    image: varilink/eosio:${VER}

    entrypoint: snapshot.sh

    volumes:
      - ./config:/config
      - data:/data

volumes:
  # nodeos data directory, Docker Compose will auto name this as eosio_data
  data:
  # keosd wallet directory, Docker Compose will auto name this as eosio_wallet
  wallet:
